services:
  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    ports:
      - 5000:80
    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./plugins/process/squared.py:/pygeoapi/pygeoapi/process/squared.py
      - ./plugins/process/shapely_functions.py:/pygeoapi/pygeoapi/process/shapely_functions.py
